[package]
name = "data-to-parquet"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
arrow = "57.1.0"
calamine = "0.32.0"
clap = { version = "4.5.53", features = ["derive"] }
parquet = "57.1.0"

[[bin]]
name = "data-to-parquet"
path = "./src/main.rs"
